name: CI - Docker Flask App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t flask-app:latest .

    - name: Run container (basic test)
      run: |
        docker run -d -p 5000:5000 --name flask_test flask-app:latest
        sleep 5
        docker ps
